#!/usr/bin/env bash
# Environment setting launcher for classic confinement snaps
# This launcher gives priority to in-snap external command and library searching, making classic confinement snaps behave "like" strict confinement snaps.  This launcher should be dropped if the snap isn't in classic confinement.
# https://github.com/Lin-Buo-Ren/snap-arch-triplet-part
# 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com> © 2018

set \
    -o errexit \
    -o errtrace \
    -o nounset \
    -o pipefail

# COMPAT: Honour SNAP_ARCH_TRIPLET when available
if test -v SNAP_ARCH_TRIPLET; then
    export X_DEBIAN_MULTIARCH_TRIPLET="${SNAP_ARCH_TRIPLET}"
fi
    
if ! test -v X_DEBIAN_MULTIARCH_TRIPLET; then
    # Markdown code syntax is not tilde expansion
    # shellcheck disable=SC2016
    printf -- \
        'classic-launch: Error: Packaging bug!  Please set the X_DEBIAN_MULTIARCH_TRIPLET environment variable by running the `debian-multiarch-triplet-provider-launch` launcher before `classic-launch`!\n' \
        1>&2
    exit 1
fi

PATH="$SNAP"/usr/sbin:"$SNAP"/usr/bin:"$SNAP"/sbin:"$SNAP"/bin:"$PATH"

if test -v LD_LIBRARY_PATH; then
    LD_LIBRARY_PATH="$LD_LIBRARY_PATH":"$SNAP"/lib:"$SNAP"/usr/lib:"$SNAP"/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}":"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}":"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}"/mesa:"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}"/mesa-egl
else
    LD_LIBRARY_PATH="$SNAP"/lib:"$SNAP"/usr/lib:"$SNAP"/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}":"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}":"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}"/mesa:"$SNAP"/usr/lib/"${X_DEBIAN_MULTIARCH_TRIPLET}"/mesa-egl
    export LD_LIBRARY_PATH
fi
LD_LIBRARY_PATH="$SNAP_LIBRARY_PATH":"$LD_LIBRARY_PATH"

exec "${@}"
