name: classic-launch
title: The classic-launch Launcher Stage Snap
# FIXME: Should use `bare` adapter when available
base: core18
version: git
summary: Setup the environment for classic confined snaps
description: |
  This stage snap ships a launcher to set-up proper environment for snaps in classic confinement.  Refer the following snapcraft forum topic for more info regarding the use of this snap:

      _snapcraft_forum_topic_title_
      _snapcraft_forum_topic_url_

grade: stable
confinement: classic

# We only ship launcher here, don't do duplicate work
# Build on s390x architecture as the build machine is least busy
architectures:
- build-on: s390x
  run-on: all

parts:
  main:
    source: snap/local/launchers
    plugin: dump
    organize:
      '*': launchers/
